/**
 * The primitives block of the README (docs/15 §2 block 5), generated: `bun packages/bench/readme/primitives.ts`
 * → .github/readme/primitives.html, pasted into README.md between the `<!-- primitives -->` markers by
 * whoever edits it next. Each row is a primitive's own `example:` from `packages/spec/primitives/*.yaml`
 * — the source the fixture was built from — beside the crop `shots.ts` took of it rendering. The spec is
 * the source of both columns, so a primitive that changes its example changes the README.
 */
import { writeFileSync, existsSync } from "node:fs";
import { primitives } from "@snypd/spec";

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
// Inline `<code>`, not `<pre>`: GitHub's table is `width: max-content`, so a `<pre>` with a 120-character
// line pushed the picture column off the right edge behind a scrollbar; `code` breaks spaces and keeps
// newlines (`white-space: break-spaces`). A newline is written as `&#10;`: an example with a blank line (`faq`'s) would otherwise
// end the HTML block under CommonMark and hand the rest of the table to markdown — `### What does help?`
// rendered as a heading of the README the first time it was pushed.
const pre = (s: string) => esc(s).replace(/\n/g, "&#10;");
const ORDER = ["cover", "tldr", "callout", "pullquote", "stat-row", "stat", "chart", "diagram", "flow", "steps", "faq", "figure", "cta"];
const rows = ORDER.map((name) => {
  const p = primitives().find((x) => x.name === name)!;
  const img = `.github/readme/primitives/${name}.png`;
  if (!existsSync(img)) throw new Error(`${img} is missing — run shots.ts first`);
  return `<tr>
<td valign="top" width="46%"><strong><code>${name}</code></strong> — ${esc(p.purpose.split(". ")[0]!.replace(/\.$/, ""))}.<br><br><code>${pre(p.example.trimEnd())}</code></td>
<td valign="top" width="54%"><img src="${img}" alt="${esc(name)} rendered by the editorial theme" width="100%"></td>
</tr>`;
});
const html = `<!-- primitives: generated by packages/bench/readme/primitives.ts — edit the spec, not this -->
<table>
${rows.join("\n")}
</table>
<!-- /primitives -->
`;
writeFileSync(".github/readme/primitives.html", html);
console.log(`.github/readme/primitives.html  ${rows.length} rows  ${(html.length / 1024).toFixed(1)} KB`);
