/**
 * Writes `bundled.ts` — the themes that ship *inside* the binary (decision 46).
 * Run after adding a theme or a theme file; `config.test.ts` regenerates and asserts no diff.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const REPO = join(import.meta.dir, "..", "..", "..");
const THEMES = join(REPO, "themes");
/** Bundled by name. A theme outside this list is a user's, lives on their disk, and is loaded from it. */
export const BUNDLED_NAMES = ["base", "editorial"] as const;
/** Text we can inline; everything else is a module and gets a lazy `import()` thunk. */
const TEXT = [".yaml", ".css", ".json"];

const ident = (s: string) => "_" + s.replace(/[^a-z0-9]+/gi, "_");
const walk = (dir: string, out: string[] = [], base = dir): string[] => {
  for (const f of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (f.name === "node_modules" || f.name.startsWith(".") || f.name === "package.json") continue;
    const p = join(dir, f.name);
    if (f.isDirectory()) walk(p, out, base); else out.push(relative(base, p).split("\\").join("/"));
  }
  return out;
};

export function generate(): string {
  const imports: string[] = [], entries: string[] = [];
  for (const name of BUNDLED_NAMES) {
    const dir = join(THEMES, name);
    const files = walk(dir);
    const h = createHash("sha1");
    for (const f of files) h.update(f).update(readFileSync(join(dir, f)));
    const text: string[] = [], mods: string[] = [];
    for (const f of files) {
      const spec = JSON.stringify(`../../../themes/${name}/${f}`);
      if (TEXT.some((e) => f.endsWith(e))) {
        const id = ident(`${name}_${f}`);
        imports.push(`import ${id} from ${spec} with { type: "text" };`);
        text.push(`      ${JSON.stringify(f)}: ${id},`);
      } else {
        // A thunk, not a static import: nothing in a theme is evaluated until a render asks for it, so
        // `mcp.coldStart` (50 ms, docs/07 D2) pays nothing for the themes sitting in the binary.
        mods.push(`      ${JSON.stringify(f)}: () => import(${spec}),`);
      }
    }
    entries.push([
      `  ${JSON.stringify(name)}: {`,
      `    hash: ${JSON.stringify(h.digest("hex"))},`,
      `    files: {`, ...text, `    },`,
      `    modules: {`, ...mods, `    },`,
      `  },`,
    ].join("\n"));
  }
  return [
    "/**",
    " * GENERATED by `bun packages/core/src/bundled.gen.ts` — do not edit.",
    " *",
    " * The themes that ship inside the binary (decision 46). Reached only when the theme is *not* on disk:",
    " * a checkout and an npm install both have `themes/`, and a user's own theme always does, so the disk",
    " * loader stays the normal path and a third-party theme is not a second-class citizen. `hash` is the",
    " * sha1 of the theme's bytes at generation time — it stands in for `themeHash` where there is no file",
    " * to stat, and it cannot go stale there, because a theme inside a binary cannot change.",
    " */",
    ...imports,
    "",
    "export interface BundledTheme {",
    "  hash: string;",
    "  /** Theme-relative path → contents, for the files that are text (theme.yaml, stylesheets). */",
    "  files: Readonly<Record<string, string>>;",
    "  /** Theme-relative path → lazy loader, for the files that are modules (layouts, primitives). */",
    "  modules: Readonly<Record<string, () => Promise<unknown>>>;",
    "}",
    "",
    "export const BUNDLED: Readonly<Record<string, BundledTheme>> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const out = join(import.meta.dir, "bundled.ts");
  writeFileSync(out, generate());
  console.log(`wrote ${out} (${BUNDLED_NAMES.join(", ")})`);
}
