/**
 * GENERATED by `bun packages/core/src/bundled.gen.ts` — do not edit.
 *
 * The themes that ship inside the binary (decision 46). Reached only when the theme is *not* on disk:
 * a checkout and an npm install both have `themes/`, and a user's own theme always does, so the disk
 * loader stays the normal path and a third-party theme is not a second-class citizen. `hash` is the
 * sha1 of the theme's bytes at generation time — it stands in for `themeHash` where there is no file
 * to stat, and it cannot go stale there, because a theme inside a binary cannot change.
 */
import _base_theme_yaml from "../../../themes/base/theme.yaml" with { type: "text" };
import _editorial_theme_css from "../../../themes/editorial/theme.css" with { type: "text" };
import _editorial_theme_yaml from "../../../themes/editorial/theme.yaml" with { type: "text" };
import _plugin_analytics_snypd_yaml from "../../../plugins/analytics/snypd.yaml" with { type: "text" };
import _plugin_autolink_snypd_yaml from "../../../plugins/autolink/snypd.yaml" with { type: "text" };
import _plugin_changelog_snypd_yaml from "../../../plugins/changelog/snypd.yaml" with { type: "text" };
import _plugin_indexnow_snypd_yaml from "../../../plugins/indexnow/snypd.yaml" with { type: "text" };

export interface BundledTheme {
  hash: string;
  /** Theme-relative path → contents, for the files that are text (theme.yaml, stylesheets). */
  files: Readonly<Record<string, string>>;
  /** Theme-relative path → lazy loader, for the files that are modules (layouts, primitives). */
  modules: Readonly<Record<string, () => Promise<unknown>>>;
}

export const BUNDLED: Readonly<Record<string, BundledTheme>> = {
  "base": {
    hash: "72232e2dc173203e195aaea5af0b150bdf22db69",
    files: {
      "theme.yaml": _base_theme_yaml,
    },
    modules: {
      "layouts/author.tsx": () => import("../../../themes/base/layouts/author.tsx"),
      "layouts/index.tsx": () => import("../../../themes/base/layouts/index.tsx"),
      "layouts/page.tsx": () => import("../../../themes/base/layouts/page.tsx"),
      "layouts/post.tsx": () => import("../../../themes/base/layouts/post.tsx"),
      "layouts/term.tsx": () => import("../../../themes/base/layouts/term.tsx"),
      "parts/entries.tsx": () => import("../../../themes/base/parts/entries.tsx"),
      "parts/footer.tsx": () => import("../../../themes/base/parts/footer.tsx"),
      "parts/header.tsx": () => import("../../../themes/base/parts/header.tsx"),
      "parts/shell.tsx": () => import("../../../themes/base/parts/shell.tsx"),
      "primitives/callout.tsx": () => import("../../../themes/base/primitives/callout.tsx"),
      "primitives/chart.tsx": () => import("../../../themes/base/primitives/chart.tsx"),
      "primitives/cover.tsx": () => import("../../../themes/base/primitives/cover.tsx"),
      "primitives/cta.tsx": () => import("../../../themes/base/primitives/cta.tsx"),
      "primitives/diagram.tsx": () => import("../../../themes/base/primitives/diagram.tsx"),
      "primitives/faq.tsx": () => import("../../../themes/base/primitives/faq.tsx"),
      "primitives/figure.tsx": () => import("../../../themes/base/primitives/figure.tsx"),
      "primitives/flow.tsx": () => import("../../../themes/base/primitives/flow.tsx"),
      "primitives/pullquote.tsx": () => import("../../../themes/base/primitives/pullquote.tsx"),
      "primitives/stat-row.tsx": () => import("../../../themes/base/primitives/stat-row.tsx"),
      "primitives/stat.tsx": () => import("../../../themes/base/primitives/stat.tsx"),
      "primitives/steps.tsx": () => import("../../../themes/base/primitives/steps.tsx"),
      "primitives/tldr.tsx": () => import("../../../themes/base/primitives/tldr.tsx"),
    },
  },
  "editorial": {
    hash: "a9cc077e879653213954c9210ad002b49dcca3dc",
    files: {
      "theme.css": _editorial_theme_css,
      "theme.yaml": _editorial_theme_yaml,
    },
    modules: {
      "parts/header.tsx": () => import("../../../themes/editorial/parts/header.tsx"),
    },
  },
};

/** The first-party plugins (docs/10 §4.8, decision 83): the same shape, the same seam, a different prefix. */
export const BUNDLED_PLUGINS: Readonly<Record<string, BundledTheme>> = {
  "analytics": {
    hash: "096b251af08506d1481d483cb74eb24fe2c8d16b",
    files: {
      "snypd.yaml": _plugin_analytics_snypd_yaml,
    },
    modules: {
      "provider.ts": () => import("../../../plugins/analytics/provider.ts"),
      "slots/beacon.tsx": () => import("../../../plugins/analytics/slots/beacon.tsx"),
      "slots/head.tsx": () => import("../../../plugins/analytics/slots/head.tsx"),
    },
  },
  "autolink": {
    hash: "5a036ac3d8dc01ae99a1a0da85148240b911048a",
    files: {
      "snypd.yaml": _plugin_autolink_snypd_yaml,
    },
    modules: {
      "transform.ts": () => import("../../../plugins/autolink/transform.ts"),
    },
  },
  "changelog": {
    hash: "c7a7a6b331250e7e90171bf84dd311495ef22a5c",
    files: {
      "snypd.yaml": _plugin_changelog_snypd_yaml,
    },
    modules: {
    },
  },
  "indexnow": {
    hash: "718dee5ba7421bf40ef78eaa9a2751d653f6f7f0",
    files: {
      "snypd.yaml": _plugin_indexnow_snypd_yaml,
    },
    modules: {
      "emit.ts": () => import("../../../plugins/indexnow/emit.ts"),
      "prompts.ts": () => import("../../../plugins/indexnow/prompts.ts"),
      "push.ts": () => import("../../../plugins/indexnow/push.ts"),
      "tools.ts": () => import("../../../plugins/indexnow/tools.ts"),
    },
  },
};
