/**
 * GENERATED by `bun packages/core/src/bundled.gen.ts` — do not edit.
 *
 * The themes that ship inside the binary (decision 46). Reached only when the theme is *not* on disk:
 * a checkout and an npm install both have `themes/`, and a user's own theme always does, so the disk
 * loader stays the normal path and a third-party theme is not a second-class citizen. `hash` is the
 * sha1 of the theme's bytes at generation time — it stands in for `themeHash` where there is no file
 * to stat, and it cannot go stale there, because a theme inside a binary cannot change.
 */
import _base_theme_yaml from "../../../themes/base/theme.yaml" with { type: "text" };
import _editorial_theme_css from "../../../themes/editorial/theme.css" with { type: "text" };
import _editorial_theme_yaml from "../../../themes/editorial/theme.yaml" with { type: "text" };
import _plugin_changelog_snypd_yaml from "../../../plugins/changelog/snypd.yaml" with { type: "text" };

export interface BundledTheme {
  hash: string;
  /** Theme-relative path → contents, for the files that are text (theme.yaml, stylesheets). */
  files: Readonly<Record<string, string>>;
  /** Theme-relative path → lazy loader, for the files that are modules (layouts, primitives). */
  modules: Readonly<Record<string, () => Promise<unknown>>>;
}

export const BUNDLED: Readonly<Record<string, BundledTheme>> = {
  "base": {
    hash: "04c9984e78699ccaf88813a5b88ce149f3664595",
    files: {
      "theme.yaml": _base_theme_yaml,
    },
    modules: {
      "layouts/author.tsx": () => import("../../../themes/base/layouts/author.tsx"),
      "layouts/index.tsx": () => import("../../../themes/base/layouts/index.tsx"),
      "layouts/page.tsx": () => import("../../../themes/base/layouts/page.tsx"),
      "layouts/post.tsx": () => import("../../../themes/base/layouts/post.tsx"),
      "layouts/term.tsx": () => import("../../../themes/base/layouts/term.tsx"),
      "parts/entries.tsx": () => import("../../../themes/base/parts/entries.tsx"),
      "parts/footer.tsx": () => import("../../../themes/base/parts/footer.tsx"),
      "parts/header.tsx": () => import("../../../themes/base/parts/header.tsx"),
      "parts/shell.tsx": () => import("../../../themes/base/parts/shell.tsx"),
      "primitives/callout.tsx": () => import("../../../themes/base/primitives/callout.tsx"),
      "primitives/chart.tsx": () => import("../../../themes/base/primitives/chart.tsx"),
      "primitives/cover.tsx": () => import("../../../themes/base/primitives/cover.tsx"),
      "primitives/cta.tsx": () => import("../../../themes/base/primitives/cta.tsx"),
      "primitives/diagram.tsx": () => import("../../../themes/base/primitives/diagram.tsx"),
      "primitives/faq.tsx": () => import("../../../themes/base/primitives/faq.tsx"),
      "primitives/figure.tsx": () => import("../../../themes/base/primitives/figure.tsx"),
      "primitives/flow.tsx": () => import("../../../themes/base/primitives/flow.tsx"),
      "primitives/pullquote.tsx": () => import("../../../themes/base/primitives/pullquote.tsx"),
      "primitives/stat-row.tsx": () => import("../../../themes/base/primitives/stat-row.tsx"),
      "primitives/stat.tsx": () => import("../../../themes/base/primitives/stat.tsx"),
      "primitives/steps.tsx": () => import("../../../themes/base/primitives/steps.tsx"),
      "primitives/tldr.tsx": () => import("../../../themes/base/primitives/tldr.tsx"),
    },
  },
  "editorial": {
    hash: "abb614def5f9612954d9ddc6bf0194fba6ffdf51",
    files: {
      "theme.css": _editorial_theme_css,
      "theme.yaml": _editorial_theme_yaml,
    },
    modules: {
      "parts/header.tsx": () => import("../../../themes/editorial/parts/header.tsx"),
    },
  },
};

/** The first-party plugins (docs/10 §4.8, decision 83): the same shape, the same seam, a different prefix. */
export const BUNDLED_PLUGINS: Readonly<Record<string, BundledTheme>> = {
  "changelog": {
    hash: "c7a7a6b331250e7e90171bf84dd311495ef22a5c",
    files: {
      "snypd.yaml": _plugin_changelog_snypd_yaml,
    },
    modules: {
    },
  },
};
