/**
 * GENERATED by `bun packages/core/src/bundled.gen.ts` — do not edit.
 *
 * The themes that ship inside the binary (decision 46). Reached only when the theme is *not* on disk:
 * a checkout and an npm install both have `themes/`, and a user's own theme always does, so the disk
 * loader stays the normal path and a third-party theme is not a second-class citizen. `hash` is the
 * sha1 of the theme's bytes at generation time — it stands in for `themeHash` where there is no file
 * to stat, and it cannot go stale there, because a theme inside a binary cannot change.
 */
import _base_theme_yaml from "../../../themes/base/theme.yaml" with { type: "text" };
import _editorial_theme_css from "../../../themes/editorial/theme.css" with { type: "text" };
import _editorial_theme_yaml from "../../../themes/editorial/theme.yaml" with { type: "text" };

export interface BundledTheme {
  hash: string;
  /** Theme-relative path → contents, for the files that are text (theme.yaml, stylesheets). */
  files: Readonly<Record<string, string>>;
  /** Theme-relative path → lazy loader, for the files that are modules (layouts, primitives). */
  modules: Readonly<Record<string, () => Promise<unknown>>>;
}

export const BUNDLED: Readonly<Record<string, BundledTheme>> = {
  "base": {
    hash: "038251b73ac26b5799c88121c3a78688ce7047d3",
    files: {
      "theme.yaml": _base_theme_yaml,
    },
    modules: {
      "layouts/author.tsx": () => import("../../../themes/base/layouts/author.tsx"),
      "layouts/entries.tsx": () => import("../../../themes/base/layouts/entries.tsx"),
      "layouts/index.tsx": () => import("../../../themes/base/layouts/index.tsx"),
      "layouts/page.tsx": () => import("../../../themes/base/layouts/page.tsx"),
      "layouts/post.tsx": () => import("../../../themes/base/layouts/post.tsx"),
      "layouts/shell.tsx": () => import("../../../themes/base/layouts/shell.tsx"),
      "layouts/term.tsx": () => import("../../../themes/base/layouts/term.tsx"),
      "primitives/callout.tsx": () => import("../../../themes/base/primitives/callout.tsx"),
      "primitives/chart.tsx": () => import("../../../themes/base/primitives/chart.tsx"),
      "primitives/cover.tsx": () => import("../../../themes/base/primitives/cover.tsx"),
      "primitives/cta.tsx": () => import("../../../themes/base/primitives/cta.tsx"),
      "primitives/diagram.tsx": () => import("../../../themes/base/primitives/diagram.tsx"),
      "primitives/faq.tsx": () => import("../../../themes/base/primitives/faq.tsx"),
      "primitives/figure.tsx": () => import("../../../themes/base/primitives/figure.tsx"),
      "primitives/flow.tsx": () => import("../../../themes/base/primitives/flow.tsx"),
      "primitives/pullquote.tsx": () => import("../../../themes/base/primitives/pullquote.tsx"),
      "primitives/stat-row.tsx": () => import("../../../themes/base/primitives/stat-row.tsx"),
      "primitives/stat.tsx": () => import("../../../themes/base/primitives/stat.tsx"),
      "primitives/steps.tsx": () => import("../../../themes/base/primitives/steps.tsx"),
      "primitives/tldr.tsx": () => import("../../../themes/base/primitives/tldr.tsx"),
    },
  },
  "editorial": {
    hash: "21b7d6956d48e9b394eac2cf1d551cbb1ebbac60",
    files: {
      "theme.css": _editorial_theme_css,
      "theme.yaml": _editorial_theme_yaml,
    },
    modules: {
    },
  },
};
