/**
 * Writes `assets.ts` — the barrel of every file that ships *inside* the binary (decision 46).
 * Run it after adding or removing a spec YAML; `spec.test.ts` regenerates and asserts no diff, so
 * forgetting fails `bun test` rather than only the release.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
export const ASSET_DIRS = ["primitives", "defaults", "detect"] as const;

const ident = (p: string) => "_" + p.replace(/[^a-z0-9]+/gi, "_");

export function generate(): string {
  const files = ASSET_DIRS.flatMap((d) =>
    readdirSync(join(ROOT, d)).filter((f) => f.endsWith(".yaml")).sort().map((f) => `${d}/${f}`));
  return [
    "/**",
    " * GENERATED by `bun packages/spec/src/assets.gen.ts` — do not edit.",
    " *",
    " * Every spec YAML as a static text import (decision 46). Static because the bundler has to *see*",
    " * the reference: `readdirSync` cannot list `$bunfs` and `import(join(dir, name))` embeds nothing,",
    " * which is why a compiled binary died on `scandir '/$bunfs/defaults'` before S18a. Used on disk",
    " * exactly as it is used in the binary, so there is one path and the tests cover the artefact.",
    " */",
    ...files.map((f) => `import ${ident(f)} from ${JSON.stringify("../" + f)} with { type: "text" };`),
    "",
    "/** Path relative to the package root → file contents. */",
    "export const ASSETS: Readonly<Record<string, string>> = {",
    ...files.map((f) => `  ${JSON.stringify(f)}: ${ident(f)},`),
    "};",
    "",
    "/** The `.yaml` names in one asset directory, sorted — `readdirSync` for files that may not be on a disk. */",
    "export function assetDir(dir: string): string[] {",
    "  const p = dir + \"/\";",
    "  return Object.keys(ASSETS).filter((k) => k.startsWith(p)).map((k) => k.slice(p.length)).sort();",
    "}",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const out = join(ROOT, "src", "assets.ts");
  writeFileSync(out, generate());
  console.log(`wrote ${out}`);
}
