/**
 * GENERATED by `bun packages/spec/src/assets.gen.ts` — do not edit.
 *
 * Every spec YAML as a static text import (decision 46). Static because the bundler has to *see*
 * the reference: `readdirSync` cannot list `$bunfs` and `import(join(dir, name))` embeds nothing,
 * which is why a compiled binary died on `scandir '/$bunfs/defaults'` before S18a. Used on disk
 * exactly as it is used in the binary, so there is one path and the tests cover the artefact.
 */
import _primitives_callout_yaml from "../primitives/callout.yaml" with { type: "text" };
import _primitives_chart_yaml from "../primitives/chart.yaml" with { type: "text" };
import _primitives_cover_yaml from "../primitives/cover.yaml" with { type: "text" };
import _primitives_cta_yaml from "../primitives/cta.yaml" with { type: "text" };
import _primitives_diagram_yaml from "../primitives/diagram.yaml" with { type: "text" };
import _primitives_faq_yaml from "../primitives/faq.yaml" with { type: "text" };
import _primitives_figure_yaml from "../primitives/figure.yaml" with { type: "text" };
import _primitives_flow_yaml from "../primitives/flow.yaml" with { type: "text" };
import _primitives_pullquote_yaml from "../primitives/pullquote.yaml" with { type: "text" };
import _primitives_stat_row_yaml from "../primitives/stat-row.yaml" with { type: "text" };
import _primitives_stat_yaml from "../primitives/stat.yaml" with { type: "text" };
import _primitives_steps_yaml from "../primitives/steps.yaml" with { type: "text" };
import _primitives_tldr_yaml from "../primitives/tldr.yaml" with { type: "text" };
import _defaults_budgets_yaml from "../defaults/budgets.yaml" with { type: "text" };
import _defaults_field_types_yaml from "../defaults/field-types.yaml" with { type: "text" };
import _defaults_statuses_yaml from "../defaults/statuses.yaml" with { type: "text" };
import _defaults_taxonomies_yaml from "../defaults/taxonomies.yaml" with { type: "text" };
import _defaults_types_yaml from "../defaults/types.yaml" with { type: "text" };
import _detect_callout_yaml from "../detect/callout.yaml" with { type: "text" };
import _detect_chart_yaml from "../detect/chart.yaml" with { type: "text" };
import _detect_cover_yaml from "../detect/cover.yaml" with { type: "text" };
import _detect_cta_yaml from "../detect/cta.yaml" with { type: "text" };
import _detect_diagram_yaml from "../detect/diagram.yaml" with { type: "text" };
import _detect_faq_yaml from "../detect/faq.yaml" with { type: "text" };
import _detect_figure_yaml from "../detect/figure.yaml" with { type: "text" };
import _detect_flow_yaml from "../detect/flow.yaml" with { type: "text" };
import _detect_pullquote_yaml from "../detect/pullquote.yaml" with { type: "text" };
import _detect_stat_row_yaml from "../detect/stat-row.yaml" with { type: "text" };
import _detect_stat_yaml from "../detect/stat.yaml" with { type: "text" };
import _detect_steps_yaml from "../detect/steps.yaml" with { type: "text" };
import _detect_tldr_yaml from "../detect/tldr.yaml" with { type: "text" };

/** Path relative to the package root → file contents. */
export const ASSETS: Readonly<Record<string, string>> = {
  "primitives/callout.yaml": _primitives_callout_yaml,
  "primitives/chart.yaml": _primitives_chart_yaml,
  "primitives/cover.yaml": _primitives_cover_yaml,
  "primitives/cta.yaml": _primitives_cta_yaml,
  "primitives/diagram.yaml": _primitives_diagram_yaml,
  "primitives/faq.yaml": _primitives_faq_yaml,
  "primitives/figure.yaml": _primitives_figure_yaml,
  "primitives/flow.yaml": _primitives_flow_yaml,
  "primitives/pullquote.yaml": _primitives_pullquote_yaml,
  "primitives/stat-row.yaml": _primitives_stat_row_yaml,
  "primitives/stat.yaml": _primitives_stat_yaml,
  "primitives/steps.yaml": _primitives_steps_yaml,
  "primitives/tldr.yaml": _primitives_tldr_yaml,
  "defaults/budgets.yaml": _defaults_budgets_yaml,
  "defaults/field-types.yaml": _defaults_field_types_yaml,
  "defaults/statuses.yaml": _defaults_statuses_yaml,
  "defaults/taxonomies.yaml": _defaults_taxonomies_yaml,
  "defaults/types.yaml": _defaults_types_yaml,
  "detect/callout.yaml": _detect_callout_yaml,
  "detect/chart.yaml": _detect_chart_yaml,
  "detect/cover.yaml": _detect_cover_yaml,
  "detect/cta.yaml": _detect_cta_yaml,
  "detect/diagram.yaml": _detect_diagram_yaml,
  "detect/faq.yaml": _detect_faq_yaml,
  "detect/figure.yaml": _detect_figure_yaml,
  "detect/flow.yaml": _detect_flow_yaml,
  "detect/pullquote.yaml": _detect_pullquote_yaml,
  "detect/stat-row.yaml": _detect_stat_row_yaml,
  "detect/stat.yaml": _detect_stat_yaml,
  "detect/steps.yaml": _detect_steps_yaml,
  "detect/tldr.yaml": _detect_tldr_yaml,
};

/** The `.yaml` names in one asset directory, sorted — `readdirSync` for files that may not be on a disk. */
export function assetDir(dir: string): string[] {
  const p = dir + "/";
  return Object.keys(ASSETS).filter((k) => k.startsWith(p)).map((k) => k.slice(p.length)).sort();
}
